stages:
  - build

docker_build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t skr20/chatapp_back:latest ./frontend/
#    - docker push example.com/example-image:latest
