stages:
  - build
 # - test
  - deploy


backend_build:
  stage: build
  trigger:
    include: backend/.gitlab-ci.yml
    #strategy: depend
  rules:
    - changes: [backend/*]

frontend_build:
  stage: build
  trigger:
    include: frontend/.gitlab-ci.yml
    #strategy: depend
  rules:
    - changes: [frontend/*]

curl_ntfy:
  stage: deploy
  image: alpine
  script:
    - apk update && apk add curl
    - curl -d "reload docker" ntfy.sh/sporting-casualty-booted
  needs:
    - job: backend_build
      optional: true
    - job: frontend_build
      optional: true


