backend:
  trigger:
    include: backend/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes: [backend/*]

frontend:
  trigger:
    include: frontend/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes: [frontend/*]

curl_ntfy:
  stage: deploy
  image: alpine
  script:
    - apk update && apk add curl
    - curl -d "reload docker" ntfy.sh/sporting-casualty-booted
  needs:
    - job: backend
    - job: frontend

