version: '3'

services:
  finalproject:
    image: node:18
    volumes:
      - ./:/finalproject
    working_dir: /finalproject
    ports:
      -  '4173:4173'
    command: bash -c 'npm i && npm run dev'