version: '3'

services:
  frontend:
    image: skr20/chatapp-backend
    restart: always
    build:
      context: frontend
      dockerfile: ./Dockerfile
    #ports:
    #  -  '80:80'

  backend:
    image: skr20/chatapp-frontend
    restart: always
    build:
      context: backend
      dockerfile: ./Dockerfile
    #ports:
    #  - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://database:27017/ChatApp
      - CORS_ORIGIN='https://chat.krusbersky.net' # change this to your domain or '*'

  database:
    image: mongo
    restart: always
    volumes:
      - 'mongodb_data:/data/db'
 
volumes:
  mongodb_data:
